---
title: "Evolutionary Game Theory Analysis of Results"
author: "Václav Ocelík"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = T, message = F, error = F, dpi = 800,
                      fig.width = 8, fig.height = 6, warning = F)
```


```{r echo = F}
library(tidyverse)
library(gridExtra)
library(cowplot)
library(ggthemes)
library(ggpmisc)
library(kableExtra)
theme_set(theme_classic())
df_outliers <- read_csv("results/outliers.csv")
```

```{r}
# Legacy Code
# x <- Sys.glob("../norm_dr_sd_min/data/coop_ratio/*.csv")
# 
# 
# for(i in x){
# 
#   tournament_type <- "hetero_dr_sd_min"
#   seed <- str_remove(i,".*data_") %>%
#     str_remove(".csv")
#   save_name <- paste0("../norm_dr_sd_min/data/coop_ratio/data_", seed, ".csv")
# 
#   df <- read_csv(i) %>%
#     mutate(tournament_type = "hetero_dr_sd_min")
#   
#   print(df)
#   write_csv(df, paste0(save_name))
# 
# }
# 
# for(i in x){
# 
#   tournament_type <- str_remove(i, "../") %>%
#     str_remove("/data/outliers/.*")
#   seed <- str_remove(i, ".*outliers/") %>%
#     str_remove("_outlier_counts.csv")
#   save_name <- paste0("../", tournament_type, "/data/outliers/", seed, "_harmonized.csv")
# 
#   df <- read_csv(i) %>%
#     select(S.D., Counts) %>%
#     mutate(seed = seed,
#            tournament_type = tournament_type)
#   write_csv(df, paste0(save_name))
# 
# }

# df_outliers_max <- do.call(rbind, lapply(Sys.glob("../*max/data/outliers/*harmonized.csv"), read_csv))
# df_outliers_min <- do.call(rbind, lapply(Sys.glob("../*min/data/outliers/*harmonized.csv"), read_csv))
# df_outliers_homo <- do.call(rbind, lapply(Sys.glob("../control_group/data/outliers/*_seed"), read_csv)) %>%
#   mutate(tournament_type = "control_group")
# df_outliers <- df_outliers_max %>%
#   rbind(df_outliers_homo) %>%
#   rbind(df_outliers_min) %>%
#   mutate(tournament_type = case_when(
#     tournament_type == "pareto_m_min" ~ "pareto_m_max",
#     tournament_type == "pareto_dr_min" ~ "pareto_dr_max",
#     tournament_type == "pareto_mdr_min" ~ "pareto_mdr_max",
#     tournament_type == "pareto_m_max" ~ "pareto_m_min",
#     tournament_type == "pareto_dr_max" ~ "pareto_dr_min",
#     tournament_type == "pareto_mdr_max" ~ "pareto_mdr_min",
#     TRUE ~ as.character(tournament_type))
#     )
# rm(df_outliers_max, df_outliers_homo, df_outliers_min)
# df_coop_homo <- do.call(rbind, lapply(Sys.glob("../control_group/data/coop_ratio/*.csv"), read_csv))
# df_coop_max <- do.call(rbind, lapply(Sys.glob("../*max/data/coop_ratio/*.csv"), read_csv))
# df_coop_min <- do.call(rbind, lapply(Sys.glob("../*min/data/coop_ratio/*.csv"), read_csv))
# df_coop <- df_coop_homo %>%
#   rbind(df_coop_max) %>%
#   rbind(df_coop_min) %>%
#   mutate(tournament_type = case_when(
#     tournament_type == "pareto_m_min" ~ "pareto_m_max",
#     tournament_type == "pareto_dr_min" ~ "pareto_dr_max",
#     tournament_type == "pareto_mdr_min" ~ "pareto_mdr_max",
#     tournament_type == "pareto_m_max" ~ "pareto_m_min",
#     tournament_type == "pareto_dr_max" ~ "pareto_dr_min",
#     tournament_type == "pareto_mdr_max" ~ "pareto_mdr_min",
#     TRUE ~ as.character(tournament_type))
#     )
# rm(df_coop_homo,df_coop_max,df_coop_min)
```



__Import data__
```{r echo=T, message=F}
df_coop <- read_csv("results/cooperation_ratio.csv")
df_outliers <- read_csv("results/outliers.csv")
```


## Cooperation Ratio

__Analysis of cooperation ratio__
```{r echo=T, message = F}
df_coop %>%
  group_by(tournament_type) %>%
  summarise(mean_coop = round(mean(coop_ratio),3),
            sd_coop = round(sd(coop_ratio),3)) %>%
  ungroup() %>%
  arrange(desc(mean_coop)) %>%
  select(`Tournament` = tournament_type, `average cooperation ratio` = mean_coop, `standard deviation` = sd_coop) %>%
  kable(caption = "Tournament types arranged by mean of cooperation ratio") %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed"))

df_coop %>%
  group_by(tournament_type) %>%
  summarise(mean_coop = round(mean(coop_ratio),3),
            sd_coop = round(sd(coop_ratio),3)) %>%
  ungroup() %>%
  arrange(desc(sd_coop)) %>%
  select(`Tournament` = tournament_type, `average cooperation ratio` = mean_coop, `standard deviation` = sd_coop) %>%
  kable(caption = "Tournament types arranged by s.d. of cooperation ratio") %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed"))

df_coop %>%
  group_by(tournament_type, seed) %>%
  summarise(mean_coop = mean(coop_ratio),
            sd_coop = sd(coop_ratio)) %>%
  ggplot(aes(x = as.factor(seed), y = mean_coop)) +
    geom_bar(stat="identity") +
    geom_errorbar(aes(ymin = mean_coop-sd_coop, ymax = mean_coop + sd_coop), width = .7) +
    facet_wrap(~tournament_type) +
    coord_flip() +
    scale_fill_grey(guide = F) +
    labs(title = "Mean cooperation ratio and standard deviation per seed, facetted by tournament type",
         y = "cooperatio ratio",
         x = " ")
```

### Comparing the control group with heterogenous groups__
```{r echo=T, message = F}
df_coop %>%
  ggplot(aes(round, coop_ratio, color = tournament_type)) +
  geom_smooth(color = "black") +
  facet_wrap(~tournament_type) +
  scale_color_grey(guide = F) 
```


## Stability 

### Comparison of All Groups


```{r echo= T, message = F}
my_formula <- y ~ x

df_outliers %>%
  ggplot() +
  geom_point(aes(S.D., Counts, color = as.factor(seed))) +
  geom_smooth(aes(S.D., Counts), color = "black") +
  facet_wrap(~tournament_type) +
      scale_color_grey(guide = F) +
  labs(title = "Smooth function applied to count of outliers on standard deviation",
       x = "standard deviation",
       y = "count of outliers")

df_outliers %>%
  select(x = S.D., y = Counts, tournament_type, seed) %>%
    ggplot(aes(x = x, y = y)) +
      geom_point(aes(x, y, color = as.factor(seed))) +
      geom_smooth(method = "lm", color = "black", se=FALSE, formula = my_formula) +
      stat_poly_eq(formula = my_formula, 
                   aes(label = paste(..eq.label.., sep = "~~~")), 
                   parse = TRUE,
                   label.x = 2) +         
      facet_wrap(~tournament_type) +
            scale_color_grey(guide = F) +
  labs(title = "Linear function applied to count of outliers on standard deviation",
       x = "standard deviation",
       y = "count of outliers")

df_outliers %>%
  filter(S.D. <= 2) %>%
  select(x = S.D., y = Counts, tournament_type, seed) %>%
    ggplot(aes(x = x, y = y)) +
      geom_point(aes(x, y, color = as.factor(seed))) +
      geom_smooth(method = "lm", color = "black", se=FALSE, formula = my_formula) +
      stat_poly_eq(formula = my_formula, 
                   aes(label = paste(..eq.label.., sep = "~~~")), 
                   parse = TRUE,
                   label.x = 2) +         
      facet_wrap(~tournament_type) +
            scale_color_grey(guide = F) +
  labs(title = "Linear function applied to count of outliers on standard deviation",
       subtitle = "Range of S.D. limited from 0 to 1.5",
       x = "standard deviation",
       y = "count of outliers")
```



```{r echo = T, message=F}
df_outliers %>%
  filter(S.D. <= 2) %>%
  group_by(tournament_type) %>%
    do({
      mod = lm(Counts ~ S.D., data = .)
      data.frame(Intercept = coef(mod)[1],
                 Slope = coef(mod)[2],
                 R2 = summary(mod)$r.squared)
    }) %>%
  arrange(desc(Intercept)) %>%
  select(`tournament type` = tournament_type, intercept = Intercept, slope = Slope, `r2` = R2) %>%
  kable() %>%
  kable_styling()

df_outliers %>%
  filter(S.D. <= 2) %>%
  group_by(tournament_type) %>%
    do({
      mod = lm(Counts ~ S.D., data = .)
      data.frame(Intercept = coef(mod)[1],
                 Slope = coef(mod)[2],
                 R2 = summary(mod)$r.squared)
    }) %>%
  arrange(desc(Slope)) %>%
  select(`tournament type` = tournament_type, intercept = Intercept, slope = Slope, `r2` = R2) %>%
  kable() %>%
  kable_styling()
```



## Determining slope and start of instability


```{r}
df_slope_intercept <- df_outliers %>%
  filter(S.D. <= 2) %>%
  group_by(as.factor(tournament_type)) %>%
    do({
      mod = lm(Counts ~ S.D., data = .)
      data.frame(Intercept = coef(mod)[1],
                 Slope = coef(mod)[2],
                 R2 = summary(mod)$r.squared)
    }) %>%
  mutate(Var = -Intercept/Slope) %>%
  select(tournament_type = `as.factor(tournament_type)`, everything()) %>%
  right_join(df_outliers)  

df_slope_intercept %>%
  mutate(Intercept = round(Intercept, 0),
         Slope = round(Slope, 0),
         Var = round(Var, 2)) %>%
  mutate(Formula = str_c("alpha:", Intercept, "m:", Slope, "v:", Var, sep = " ")) %>%
  ggplot() +
  geom_point(aes(S.D., Counts, color = as.factor(seed))) +
  geom_abline(aes(intercept = Intercept, slope = Slope)) +
  geom_hline(yintercept = 0) +
  geom_text(aes(2.2, 300, label = Formula), size = 2.5) +
  facet_wrap(~tournament_type) +
              scale_color_grey(guide = F) +
  labs(title = "Linear function applied to count of outliers on standard deviation",
       subtitle = "Slope calculated for S.D. < 2",
       x = "standard deviation",
       y = "count of outliers")

```

